steps:
  # Run linter for go project
  - name: golang:1.16
    env: ['GO111MODULE=off']
    args: ['go', 'vet', './...']

      #Docker build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: sh
    args:
      - '-c'
      - 'docker build --file=Dockerfile -t us-central1-docker.pkg.dev/$PROJECT_ID/internship-repo/test-go-app:$BRANCH_NAME-$(date +$%F)-$SHORT_SHA .'