steps:
  # Run linter for go project
  - name: golang:1.16
    env: ['GO111MODULE=off']
    args: ['go', 'vet', './src/...']

  #Calculate Docker image tag
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" && -z "$TAG_NAME" ]] 
        then
          dateOfImage=$(date '+%d-%m-%Y')
          tag=":$BRANCH_NAME-${dateOfImage}-$SHORT_SHA"
          echo "Running on default branch '$BRANCH_NAME': tag = '${tag}'"
        else
          tag=":$TAG_NAME"
          echo "Running on branch '$BRANCH_NAME': tag = $tag"
        fi
        echo $tag > /image_info_volume/file
    volumes:
      - name: tag-info
        path: '/image_info_volume'

    #Docker build & push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        tag=$(cat /image_info_volume/file)
        docker build --file Dockerfile --tag ${_IMAGE_REPO_NAME}${tag} --build-arg VERSION=${tag} . &&
        docker push ${_IMAGE_REPO_NAME}${tag}
    volumes:
      - name: tag-info
        path: '/image_info_volume'

  #Delpoy via Helm
  - name: 'gcr.io/$PROJECT_ID/helm'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        tag=$(cat /image_info_volume/file)
        gcloud container clusters get-credentials --project=${PROJECT_ID} --zone=${_VM_ZONE_NAME} ${_CLUSTER_NAME}
        echo "Running: helm repo update"
        helm repo list && helm repo update || true
        helm upgrade --install my-go-app-$BRANCH_NAME app-chart/ --set container.image=${_IMAGE_REPO_NAME}${tag} --set path.prefix=$BRANCH_NAME
    volumes:
      - name: tag-info
        path: '/image_info_volume'

#     #Deploy to GKE
#  - name: 'gcr.io/cloud-builders/gke-deploy'
#    entrypoint: /bin/bash
#    args:
#      - '-c'
#      - |
#        tag=$(cat /image_info_volume/file)
#        gke-deploy run -f '${_APP_DEPLOYMENT_DIR}/deployment-$BRANCH_NAME.yaml' -i ${_IMAGE_REPO_NAME}${tag} -a test-go-app-$BRANCH_NAME -v 1.0.0 -o expanded -c ${_CLUSTER_NAME} -l ${_VM_ZONE_NAME}
#        gke-deploy run -f '$_APP_DEPLOYMENT_DIR/service-$BRANCH_NAME.yaml'
#    volumes:
#      - name: tag-info
#        path: '/image_info_volume'
#
#  - name: 'gcr.io/cloud-builders/kubectl'
#    entrypoint: /bin/bash
#    args:
#      - '-c'
#      - |
#        kubectl create clusterrolebinding cluster-admin-binding \
#        --clusterrole cluster-admin \
#        --user $(gcloud config get-value account)
#        kubectl apply -f 'https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.5.1/deploy/static/provider/cloud/deploy.yaml'
#        kubectl wait --namespace ingress-nginx \
#        --for=condition=ready pod \
#        --selector=app.kubernetes.io/component=controller \
#        --timeout=120s
#        kubectl apply -f '${_APP_DEPLOYMENT_DIR}/ingress-$BRANCH_NAME.yaml'

substitutions:
  _APP_DEPLOYMENT_DIR: './app-deployment'
  _VM_ZONE_NAME: 'europe-west6-b'
  _VM_INSTANCE_NAME: 'terraform-instance'
  _CLUSTER_NAME: 'internship-166-375809-prod-gke'
  _CONTAINER_PORT: '8000'
  _CONTAINER_NAME: 'test-go-app'
  _IMAGE_REPO_NAME: 'us-central1-docker.pkg.dev/${PROJECT_ID}/internship-repo/test-go-app'