steps:
  # Run linter for go project
  - name: golang:1.16
    id: linter-step
    env: ['GO111MODULE=off']
    args: ['go', 'vet', './...']

  #Docker build & push
  - name: 'gcr.io/cloud-builders/docker'
    id: build-push-image-step
    waitFor:
      - linter-step
    entrypoint: /bin/bash
    args:
      - '-c'
      - |  
        if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "dev" && -z "$TAG_NAME" ]] 
        then
          dateOfImage=$(date '+%d-%m-%Y')
          tag=":$BRANCH_NAME-${dateOfImage}-$SHORT_SHA"
          echo "Running on default branch '$BRANCH_NAME': tag = '${tag}'"
        else
          tag=":$TAG_NAME"
          echo "Running on branch '$BRANCH_NAME': tag = $tag"
        fi
        docker build --file Dockerfile --tag us-central1-docker.pkg.dev/$PROJECT_ID/internship-repo/test-go-app${tag} . &&
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/internship-repo/test-go-app${tag}

  #Deploy container
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - |
        gcloud compute ssh --zone "us-central1-a" "internship-test-instance"  --project "internship-166-375809" &&
        echo 'This is vm's shell!'