apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    matchLabels:
      app: test-go-app
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000