apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: test-go-app-main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000