apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Values.branch.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000