name: Docker image build
on:
  workflow_dispatch: {}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set short sha
        id: vars
        run: |
          sha_short=${{ github.sha }}
          echo SHORT_SHA = $sha_short | cut -c 1-8 >> GITHUB_ENV
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
        
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::979063481013:role/github-actions-ecr
          aws-region: us-east-1

      - name: Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: hello_repo
          IMAGE_TAG: ${{ github.ref_name }}-${{ env.SHORT_SHA }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
