name: Docker image build
on:
  workflow_dispatch: {}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::979063481013:role/github-actions-ecr-role
          aws-region: us-east-1

      - name: Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
